# Generated by Django 3.0.6 on 2020-05-27 08:46

from django.db import migrations, models
import firebase_authentication.managers


class Migration(migrations.Migration):

    dependencies = [
        ('firebase_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', firebase_authentication.managers.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='display name'),
        ),
    ]
