# Generated by Django 3.0.7 on 2020-07-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firebase_authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="picture",
            field=models.URLField(blank=True, null=True, verbose_name="picture"),
        ),
    ]
