# Generated by Django 3.0.7 on 2020-07-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firebase_authentication", "0002_auto_20200527_0846"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="display_name",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="display name"
            ),
        ),
    ]
