# Generated by Django 3.0.7 on 2020-07-05 11:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wilt_user", "0003_auto_20200705_2005"),
    ]

    operations = [
        migrations.CreateModel(
            name="Til",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="til id"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PL", "Plan"),
                            ("DS", "Design"),
                            ("DV", "Develop"),
                            ("MK", "Marketing"),
                            ("DT", "Data"),
                        ],
                        max_length=2,
                        verbose_name="category",
                    ),
                ),
                ("title", models.TextField(verbose_name="title")),
                ("content", models.TextField(verbose_name="content")),
                ("is_public", models.BooleanField(default=True, verbose_name="public")),
                (
                    "date_created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="date created",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wilt_user.WiltUser",
                    ),
                ),
            ],
            options={"verbose_name": "til", "verbose_name_plural": "tils",},
        ),
    ]
