# Generated by Django 3.0.7 on 2020-07-08 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wilt_til", "0002_auto_20200708_1429"),
    ]

    operations = [
        migrations.RenameField(model_name="til", old_name="author", new_name="user",),
    ]
