# Generated by Django 3.0.7 on 2020-07-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wilt_til", "0005_auto_20200708_1620"),
    ]

    operations = [
        migrations.AddField(
            model_name="til",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="is_active"),
        ),
    ]
