# Generated by Django 3.0.7 on 2020-07-09 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("wilt_til", "0006_til_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="til",
            name="date_created",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="date created",
            ),
        ),
        migrations.AlterField(
            model_name="til",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="is active"),
        ),
    ]
