# Generated by Django 3.0.7 on 2020-07-09 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("wilt_til", "0007_auto_20200709_2125"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="date_created",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="date created",
            ),
        ),
        migrations.AlterField(
            model_name="clap",
            name="date_created",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="date created",
            ),
        ),
    ]
