# Generated by Django 3.0.7 on 2020-07-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wilt_til", "0009_tag_tiltag"),
    ]

    operations = [
        migrations.AddField(
            model_name="til",
            name="tags",
            field=models.ManyToManyField(related_name="til_tags", to="wilt_til.Tag"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.DeleteModel(name="TilTag",),
    ]
