# Generated by Django 3.0.7 on 2020-07-07 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import firebase_authentication.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("firebase_authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WiltUser",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="company name",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="job title"
                    ),
                ),
                (
                    "career_year",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=3,
                        null=True,
                        verbose_name="company name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="user description"
                    ),
                ),
                (
                    "web_link",
                    models.TextField(blank=True, null=True, verbose_name="web link"),
                ),
            ],
            options={"verbose_name": "user", "verbose_name_plural": "users",},
            bases=("firebase_authentication.user",),
            managers=[("objects", firebase_authentication.managers.UserManager()),],
        ),
    ]
