# Generated by Django 3.0.7 on 2020-07-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wilt_user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wiltuser",
            name="career_year",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=3,
                null=True,
                verbose_name="company name",
            ),
        ),
        migrations.AlterField(
            model_name="wiltuser",
            name="company_name",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="company name"
            ),
        ),
        migrations.AlterField(
            model_name="wiltuser",
            name="job_title",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="job title"
            ),
        ),
    ]
