# Generated by Django 3.0.7 on 2020-07-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wilt_user', '0002_userfollow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiltuser',
            name='job_title',
            field=models.CharField(blank=True, choices=[('PL', 'Planer'), ('DS', 'Designer'), ('DV', 'Developer'), ('MK', 'Marketer'), ('DT', 'DataScientist')], max_length=2, null=True, verbose_name='job title'),
        ),
    ]
