# Generated by Django 3.0.7 on 2020-07-19 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wilt_backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="bookmark", table="bookmark",),
        migrations.AlterModelTable(name="clap", table="clap",),
        migrations.AlterModelTable(name="til", table="til",),
        migrations.AlterModelTable(name="userfollow", table="user_follow",),
        migrations.AlterModelTable(name="wiltuser", table="wilt_user",),
    ]
