# Generated by Django 3.0.7 on 2020-07-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wilt_backend", "0004_logsearch"),
    ]

    operations = [
        migrations.AddField(
            model_name="logsearch",
            name="search_entity",
            field=models.CharField(default="test", max_length=5, verbose_name="entity"),
            preserve_default=False,
        ),
    ]
