# Generated by Django 3.0.7 on 2020-08-23 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wilt_backend', '0005_logsearch_search_entity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='plant id')),
                ('plant_id', models.SmallIntegerField(verbose_name='plant_id')),
                ('plant_name', models.CharField(max_length=10, verbose_name='plant_name')),
                ('til_count', models.SmallIntegerField(verbose_name='til_count')),
                ('satellite', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='satellite')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date created')),
                ('completed_date', models.DateField(blank=True, default=None, null=True, verbose_name='completed_date')),
                ('til', models.ManyToManyField(related_name='plant_tils', to='wilt_backend.Til')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'plant',
                'verbose_name_plural': 'plant',
                'db_table': 'plant',
                'ordering': ('date_created',),
            },
        ),
    ]
