# Generated by Django 3.0.7 on 2020-08-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wilt_backend', '0006_plant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheerUpSentence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='cheerup id')),
                ('type', models.SmallIntegerField(choices=[(0, '일반 응원문구'), (1, '5일간 작성하지 않을 때 문구')], default=0, help_text='문구 타입을 설정해주세요', verbose_name='type')),
                ('text', models.CharField(max_length=255, verbose_name='text')),
                ('start_count', models.SmallIntegerField(default=0, verbose_name='start_count')),
                ('end_count', models.SmallIntegerField(verbose_name='end_count')),
            ],
        ),
    ]
