# Generated by Django 3.0.7 on 2020-08-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wilt_backend', '0008_auto_20200828_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='finish',
            field=models.BooleanField(default=False, verbose_name='finish'),
        ),
    ]
