# Generated by Django 3.0.7 on 2020-07-21 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("wilt_policy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="S3AuthInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "date_created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="date created",
                    ),
                ),
                (
                    "access_key_id",
                    models.CharField(max_length=50, verbose_name="access key id"),
                ),
                (
                    "secret_key_id",
                    models.CharField(max_length=50, verbose_name="secret key id"),
                ),
                ("region", models.CharField(max_length=20, verbose_name="region")),
                ("s3_endpoint", models.URLField(verbose_name="s3 endpont")),
                (
                    "algorithm",
                    models.CharField(max_length=20, verbose_name="algorithm"),
                ),
                ("acl", models.CharField(max_length=20, verbose_name="acl")),
            ],
            options={"db_table": "S3_auth_info", "ordering": ["-date_created"],},
        ),
    ]
